from flask import Flask, request, jsonify, render_template, send_from_directory
from flask_cors import CORS
import sqlite3
import os
import joblib  # Import joblib for model loading
from sklearn.ensemble import RandomForestClassifier # Import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer # Import CountVectorizer

app = Flask(__name__, static_folder='../frontend')
CORS(app)

DB_PATH = 'appointments.db'

# Paths for the trained model and vectorizer
# These files are generated by train_model.py
MODEL_PATH = 'random_forest_model.pkl' # Path relative to the backend directory
VECTORIZER_PATH = 'count_vectorizer.pkl' # Path relative to the backend directory
random_forest_model = None
count_vectorizer = None # Variable to hold the loaded vectorizer

def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS appointments (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        patient_email TEXT,
        doctor TEXT,
        symptoms TEXT,
        status TEXT,
        details_sent INTEGER DEFAULT 0
    )''')
    conn.commit()
    conn.close()

init_db()

# Load the model and vectorizer on application startup
try:
    model_full_path = os.path.join(os.path.dirname(__file__), MODEL_PATH)
    vectorizer_full_path = os.path.join(os.path.dirname(__file__), VECTORIZER_PATH)
    
    random_forest_model = joblib.load(model_full_path)
    count_vectorizer = joblib.load(vectorizer_full_path)
    print(f"Random Forest model loaded successfully from {model_full_path}")
    print(f"CountVectorizer loaded successfully from {vectorizer_full_path}")
except FileNotFoundError:
    print(f"Warning: Model or vectorizer file not found. Please train and save them using train_model.py.")
    # You might want to handle this case appropriately,
    # e.g., by using a default recommendation or raising an error
except Exception as e:
    print(f"Error loading model or vectorizer: {e}")

@app.route('/')
def home():
    return send_from_directory(app.static_folder, 'index.html')

@app.route('/<path:path>')
def serve_static(path):
    return send_from_directory(app.static_folder, path)

@app.route('/login', methods=['POST'])
def login():
    data = request.json
    email = data.get('email')
    password = data.get('password')
    if email == 'admin@gmail.com' and password == 'admin':
        return jsonify({"role": "admin", "status": "success", "email": email})
    elif email == 'patient@gmail.com' and password == 'patient':
        return jsonify({"role": "patient", "status": "success", "email": email})
    return jsonify({"status": "error", "message": "Invalid credentials"})

@app.route('/recommend', methods=['POST'])
def recommend():
    symptoms = request.json.get('symptoms', '').lower()

    if random_forest_model and count_vectorizer:
        try:
            # --- Preprocess symptoms using the loaded vectorizer ---
            # Transform the input symptoms using the same vectorizer used during training
            symptoms_features = count_vectorizer.transform([symptoms]) # count_vectorizer expects an iterable

            # --- Make prediction using the loaded model ---
            predicted_doctor = random_forest_model.predict(symptoms_features)[0]

            # You might want to map the predicted class back to a readable doctor name
            # For now, we'll just return the prediction
            return jsonify({"doctor": predicted_doctor, "explanation": "Recommendation based on Random Forest model."})

        except Exception as e:
            print(f"Error during model prediction: {e}")
            return jsonify({"status": "error", "message": "Error predicting doctor recommendation."})
    else:
        # Fallback if model or vectorizer is not loaded
        # You can keep the old rule-based logic or return a specific message
        print("Model or vectorizer not loaded, using fallback.")
        if "fever" in symptoms or "cough" in symptoms:
            return jsonify({"doctor": "Dr. Ravi - General Physician", "explanation": "Fever & cough suggest general physician (fallback)."})
        return jsonify({"doctor": "Dr. Priya - Specialist", "explanation": "Based on symptoms, a specialist is suitable (fallback)."})

@app.route('/book', methods=['POST'])
def book():
    data = request.json
    patient_email = data.get('email')
    doctor = data.get('doctor')
    symptoms = data.get('symptoms')
    status = 'booked'
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('INSERT INTO appointments (patient_email, doctor, symptoms, status) VALUES (?, ?, ?, ?)',
              (patient_email, doctor, symptoms, status))
    conn.commit()
    appointment_id = c.lastrowid
    conn.close()
    return jsonify({"status": "booked", "appointment_id": appointment_id})

@app.route('/appointments', methods=['GET'])
def get_appointments():
    email = request.args.get('email')
    role = request.args.get('role')
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    if role == 'admin':
        c.execute('SELECT * FROM appointments')
    else:
        c.execute('SELECT * FROM appointments WHERE patient_email = ?', (email,))
    rows = c.fetchall()
    conn.close()
    appointments = [
        {"id": row[0], "patient_email": row[1], "doctor": row[2], "symptoms": row[3], "status": row[4], "details_sent": bool(row[5])}
        for row in rows
    ]
    return jsonify(appointments)

@app.route('/send_appointment', methods=['POST'])
def send_appointment():
    data = request.json
    appointment_id = data.get('appointment_id')
    # Simulate sending SMS/email
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute('UPDATE appointments SET details_sent = 1 WHERE id = ?', (appointment_id,))
    conn.commit()
    conn.close()
    return jsonify({"status": "sent"})

if __name__ == '__main__':
    app.run(debug=True)
